

services:
  web:
    build: .
    command: ["sh", "./scripts/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: syllable_division
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  postgres_data: